# Generated by Django 2.0.2 on 2018-02-17 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='city name')),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name of garden')),
                ('slug', models.SlugField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='GardenAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='street address')),
            ],
        ),
        migrations.CreateModel(
            name='GardenAddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('py', 'Physical'), ('ml', 'Mailing')], default='py', max_length=2, verbose_name='type of address')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('short_name', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='state short name')),
                ('name', models.CharField(max_length=50, verbose_name='state full name')),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='zip code')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.City', verbose_name='the related zip code')),
            ],
        ),
        migrations.AddField(
            model_name='gardenaddress',
            name='address_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.GardenAddressType', verbose_name='the related address type'),
        ),
        migrations.AddField(
            model_name='gardenaddress',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.ZipCode', verbose_name='the related garden address'),
        ),
        migrations.AddField(
            model_name='garden',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.GardenAddress', verbose_name='the related garden'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.State', verbose_name='the related city'),
        ),
    ]
