# Generated by Django 2.0.2 on 2018-03-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='garden_author',
            new_name='created_by',
        ),
    ]
