# Generated by Django 2.0.2 on 2018-02-17 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.State', verbose_name='the related state'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.GardenAddress', verbose_name='the related garden address'),
        ),
        migrations.AlterField(
            model_name='gardenaddress',
            name='zip_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.ZipCode', verbose_name='the related zip code'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardens.City', verbose_name='the related city'),
        ),
    ]
