# Generated by Django 2.0.2 on 2018-02-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_auto_20180217_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='garden',
            unique_together={('address', 'name')},
        ),
    ]
