# Generated by Django 2.0.2 on 2018-03-04 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_auto_20180304_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.AlterUniqueTogether(
            name='zipcode',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='zipcode',
            name='city',
        ),
        migrations.RemoveField(
            model_name='gardenaddress',
            name='zip_code',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
