# Generated by Django 2.0.2 on 2018-03-04 02:44

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_auto_20180304_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenaddress',
            name='city',
            field=models.CharField(default='Philadelphia', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='gardenaddress',
            name='state',
            field=localflavor.us.models.USStateField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gardenaddress',
            name='usps_code',
            field=localflavor.us.models.USPostalCodeField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gardenaddress',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(default=1, max_length=10, verbose_name='zip code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garden',
            name='description',
            field=models.CharField(blank=True, default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gardenaddress',
            name='address',
            field=models.CharField(max_length=50, verbose_name='street address'),
        ),
    ]
