# Generated by Django 2.0.2 on 2018-03-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_auto_20180304_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenaddress',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
    ]
