# Generated by Django 2.0.2 on 2018-03-04 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_auto_20180304_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='gardenaddress',
            name='usps_code',
        ),
        migrations.DeleteModel(
            name='GardenAddressType',
        ),
    ]
