# Generated by Django 2.0 on 2018-03-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_auto_20180301_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='slug of garden'),
        ),
    ]
