# Generated by Django 2.0 on 2018-03-02 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0006_auto_20180301_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden',
            name='garden_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
