# Generated by Django 2.0.2 on 2018-03-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0007_auto_20180302_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='address',
            field=models.ManyToManyField(to='gardens.GardenAddress', verbose_name='the related garden address'),
        ),
        migrations.AlterUniqueTogether(
            name='garden',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='garden',
            name='address',
        ),
    ]
