# Generated by Django 2.0.2 on 2018-03-04 03:06

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0007_gardenaddress_address_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gardenaddress',
            options={'ordering': ['address_type', 'city']},
        ),
        migrations.AlterField(
            model_name='garden',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gardens.GardenAddress', verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='garden',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='gardenaddress',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2, verbose_name='state'),
        ),
    ]
