# Generated by Django 2.0.2 on 2018-03-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0008_auto_20180302_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='address',
            field=models.ManyToManyField(to='gardens.GardenAddress'),
        ),
    ]
