# Generated by Django 2.0.2 on 2018-03-03 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0009_auto_20180302_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garden',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='garden',
            name='address',
        ),
    ]
