# Generated by Django 2.0.2 on 2018-03-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0011_auto_20180303_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='garden',
            unique_together=set(),
        ),
    ]
