# Generated by Django 2.0.2 on 2018-03-03 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0012_auto_20180303_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='address',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='gardens.GardenAddress',
                verbose_name='the related garden address'),
            preserve_default=False,
        ),
    ]
